import React from 'react';
import { Booking, Car } from '../types';
import { ShieldCheck, CalendarCheck, Coins, CirclePlay } from 'lucide-react';

/**
 * Props expected by the StatsGrid component.
 * Think of props like arguments to a function in JavaScript.
 */
interface StatsGridProps {
  bookings: Booking[];
  cars: Car[];
}

/**
 * StatsGrid Component
 * This section calculates useful real-time business statistics
 * based on our active fleet size and registered booking array.
 */
export default function StatsGrid({ bookings, cars }: StatsGridProps) {
  // 1st calculation: Standard total vehicles available
  const totalFleetSize = cars.length;

  // 2nd calculation: Total active or confirmed bookings
  const confirmedBookingsCount = bookings.filter(b => b.status === 'Confirmed').length;
  const pendingBookingsCount = bookings.filter(b => b.status === 'Pending').length;

  // 3rd calculation: Summing all revenue generated by non-cancelled bookings
  const totalIncome = bookings
    .filter(b => b.status !== 'Cancelled')
    .reduce((sum, booking) => sum + booking.totalCost, 0);

  return (
    <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4 mb-6">
      
      {/* Box 1: Total Fleet */}
      <div className="bg-white p-5 rounded-2xl border border-slate-100 shadow-xs flex items-center gap-4 hover:border-blue-200 transition-all duration-300">
        <div className="p-3.5 rounded-xl bg-blue-50 text-blue-600">
          <CirclePlay className="w-6 h-6" />
        </div>
        <div>
          <p className="text-xs text-slate-400 font-medium uppercase tracking-wider">Available Fleet Size</p>
          <h3 className="text-2xl font-bold font-mono text-slate-800">{totalFleetSize} Vehicles</h3>
          <p className="text-[11px] text-slate-400 mt-0.5">Diverse models ready to rent</p>
        </div>
      </div>

      {/* Box 2: Pending Approval */}
      <div className="bg-white p-5 rounded-2xl border border-slate-100 shadow-xs flex items-center gap-4 hover:border-amber-200 transition-all duration-300">
        <div className="p-3.5 rounded-xl bg-amber-50 text-amber-600">
          <ShieldCheck className="w-6 h-6 animate-pulse" />
        </div>
        <div>
          <p className="text-xs text-slate-400 font-medium uppercase tracking-wider">Pending Bookings</p>
          <h3 className="text-2xl font-bold font-mono text-slate-800">{pendingBookingsCount} Requests</h3>
          <p className="text-[11px] text-slate-400 mt-0.5">Need dispatcher confirmation</p>
        </div>
      </div>

      {/* Box 3: Confirmed Reservations */}
      <div className="bg-white p-5 rounded-2xl border border-slate-100 shadow-xs flex items-center gap-4 hover:border-emerald-200 transition-all duration-300">
        <div className="p-3.5 rounded-xl bg-emerald-50 text-emerald-600">
          <CalendarCheck className="w-6 h-6" />
        </div>
        <div>
          <p className="text-xs text-slate-400 font-medium uppercase tracking-wider">Confirmed Trips</p>
          <h3 className="text-2xl font-bold font-mono text-slate-800">{confirmedBookingsCount} Active</h3>
          <p className="text-[11px] text-slate-400 mt-0.5">Assigned to drivers & sanitized</p>
        </div>
      </div>

      {/* Box 4: Simulated Revenue */}
      <div className="bg-white p-5 rounded-2xl border border-slate-100 shadow-xs flex items-center gap-4 hover:border-rose-200 transition-all duration-300">
        <div className="p-3.5 rounded-xl bg-rose-50 text-rose-600">
          <Coins className="w-6 h-6" />
        </div>
        <div>
          <p className="text-xs text-slate-400 font-medium uppercase tracking-wider">Calculated Revenue</p>
          <h3 className="text-2xl font-bold font-mono text-rose-600">${totalIncome.toFixed(2)}</h3>
          <p className="text-[11px] text-slate-400 mt-0.5">From {bookings.length - bookings.filter(b=>b.status==='Cancelled').length} paid rental invoices</p>
        </div>
      </div>

    </div>
  );
}
